# Generated by Django 3.0.6 on 2020-06-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200603_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('content', models.CharField(max_length=2048)),
                ('author', models.CharField(max_length=512)),
                ('post_date_time', models.DateTimeField()),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='agree_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='disagree_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
            preserve_default=False,
        ),
    ]
