# Generated by Django 3.0.6 on 2020-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200603_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
