# Generated by Django 3.0.6 on 2020-06-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_date_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=512),
        ),
    ]
