# Generated by Django 3.0.6 on 2020-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200603_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='agree_number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='disagree_number',
        ),
    ]
