name: adityagurjar
description: My portfolio website.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  
  provider: any
  solid_bottom_sheet: ^0.1.9
  url_launcher: ^5.4.10
  connectivity: ^0.4.8+1
  test: ^1.14.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - assets/
  fonts:
  - family: GoogleSansRegular
    fonts:
      - asset: assets/GoogleSansRegular.ttf
